# Generated by Django 4.1 on 2022-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
