# Generated by Django 4.1 on 2022-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_enemy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
